### PR TITLE
Correct the word error-proof

### PR DESCRIPTION
**Pull request by zeienko-vitalii**
## Status

**READY**

## Description

Minor change in the documentation. 

**_error-prone_**'s meaning is tending to make or cause errors. Which I assume is mistakenly used here.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by zeienko-vitalii** [comment]
@yardexx Please take a look at this PR. 
Much appreciated 🙂

**Review by yardexx — APPROVED** [review]
Looking good 👍

**Comment by yardexx** [comment]
Merged.

Thx for PR :)

**Comment by zeienko-vitalii** [comment]
My pleasure 🙂

**Pull request merged**
